"""add_user_post_comment_fields

Revision ID: 86b08af29eae
Revises: d7a1902b5806
Create Date: 2025-04-30 00:29:16.495601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86b08af29eae'
down_revision: Union[str, None] = 'd7a1902b5806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'comments', 'comments', ['parent_id'], ['id'])
    op.add_column('posts', sa.Column('title', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('visibility', sa.Enum('PUBLIC', 'FRIENDS', 'PRIVATE', name='visibilitytype'), nullable=True))
    op.add_column('posts', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profile_image_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('cover_image_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'role')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'cover_image_url')
    op.drop_column('users', 'profile_image_url')
    op.drop_column('users', 'bio')
    op.drop_column('posts', 'updated_at')
    op.drop_column('posts', 'visibility')
    op.drop_column('posts', 'image_url')
    op.drop_column('posts', 'title')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'updated_at')
    op.drop_column('comments', 'parent_id')
    # ### end Alembic commands ###
